spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tinyurl}?serverTimezone=UTC
    username: ${DB_USERNAME:springUser}
    password: ${DB_PASSWORD:ThePassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
    hibernate:
      ddl-auto: update
  
server:
  port: 8899
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false